s = set()
n = input("Enter The Number: ")
s.add(int(n))
n = input("Enter The Number: ")
s.add(int(n))
n = input("Enter The Number: ")
s.add(int(n))
n = input("Enter The Number: ")
s.add(int(n))
n = input("Enter The Number: ")
s.add(int(n))
n = input("Enter The Number: ")
s.add(int(n))
n = input("Enter The Number: ")
s.add(int(n))
print(s)